/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemas_distribuidos_dama;

import java.awt.Color;

/**
 *
 * @author Emeson
 */
public class Tabuleiro extends javax.swing.JFrame {

    //criando variaveis jogando contra a maquina
    boolean jogador1Ativo = true;
    boolean jogador2Ativo = false;    
   
    public Tabuleiro() {
        initComponents();

        
        pedrasJogador1(); //metodo colocado aqui para que quando execultar carregue as pedras de uma cor logo de inicio.
        pedrasJogador2(); //metodo colocado aqui para que quando execultar carregue as pedras de outra cor logo de inicio.
    }
    //aqui alterna entre avez de cada jogador
public void jogdorAtivo(){ 
    if (jogador1Ativo == true) {
        
        jogador1Ativo = false;
        jogador2Ativo = true;
    } else {
        jogador1Ativo = true;
        jogador2Ativo = false;
    }
//    jogadorVencedor();
    //jogador2Vencedor();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt45 = new javax.swing.JButton();
        bt56 = new javax.swing.JButton();
        bt57 = new javax.swing.JButton();
        bt50 = new javax.swing.JButton();
        bt51 = new javax.swing.JButton();
        bt52 = new javax.swing.JButton();
        bt53 = new javax.swing.JButton();
        bt54 = new javax.swing.JButton();
        bt55 = new javax.swing.JButton();
        bt66 = new javax.swing.JButton();
        bt05 = new javax.swing.JButton();
        bt67 = new javax.swing.JButton();
        bt06 = new javax.swing.JButton();
        bt60 = new javax.swing.JButton();
        bt07 = new javax.swing.JButton();
        bt61 = new javax.swing.JButton();
        bt16 = new javax.swing.JButton();
        bt62 = new javax.swing.JButton();
        bt17 = new javax.swing.JButton();
        bt63 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt64 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt13 = new javax.swing.JButton();
        bt14 = new javax.swing.JButton();
        bt00 = new javax.swing.JButton();
        bt01 = new javax.swing.JButton();
        bt02 = new javax.swing.JButton();
        bt03 = new javax.swing.JButton();
        bt04 = new javax.swing.JButton();
        bt65 = new javax.swing.JButton();
        bt76 = new javax.swing.JButton();
        bt77 = new javax.swing.JButton();
        bt70 = new javax.swing.JButton();
        bt15 = new javax.swing.JButton();
        bt71 = new javax.swing.JButton();
        bt26 = new javax.swing.JButton();
        bt72 = new javax.swing.JButton();
        bt27 = new javax.swing.JButton();
        bt73 = new javax.swing.JButton();
        bt20 = new javax.swing.JButton();
        bt74 = new javax.swing.JButton();
        bt21 = new javax.swing.JButton();
        bt75 = new javax.swing.JButton();
        bt22 = new javax.swing.JButton();
        bt23 = new javax.swing.JButton();
        bt24 = new javax.swing.JButton();
        bt25 = new javax.swing.JButton();
        bt36 = new javax.swing.JButton();
        bt37 = new javax.swing.JButton();
        bt30 = new javax.swing.JButton();
        bt31 = new javax.swing.JButton();
        bt32 = new javax.swing.JButton();
        bt33 = new javax.swing.JButton();
        bt34 = new javax.swing.JButton();
        bt35 = new javax.swing.JButton();
        bt46 = new javax.swing.JButton();
        bt47 = new javax.swing.JButton();
        bt40 = new javax.swing.JButton();
        bt41 = new javax.swing.JButton();
        bt42 = new javax.swing.JButton();
        bt43 = new javax.swing.JButton();
        bt44 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumeroDeVitoriasDoJogador01 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NumeroDeVitóriasDoJogaador02 = new javax.swing.JLabel();
        NumeroDeEmpates = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btNovoJogo = new javax.swing.JButton();
        btSobreJogo = new javax.swing.JButton();
        btSairJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabuleiro de Damas");
        setBackground(new java.awt.Color(0, 204, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("TABULEIRO DE DAMAS");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bt45.setBackground(new java.awt.Color(0, 0, 0));
        bt45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt45ActionPerformed(evt);
            }
        });

        bt56.setBackground(new java.awt.Color(0, 0, 0));
        bt56.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt56ActionPerformed(evt);
            }
        });

        bt57.setBackground(new java.awt.Color(255, 255, 255));
        bt57.setForeground(new java.awt.Color(255, 255, 255));
        bt57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt57ActionPerformed(evt);
            }
        });

        bt50.setBackground(new java.awt.Color(0, 0, 0));
        bt50.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt50ActionPerformed(evt);
            }
        });

        bt51.setBackground(new java.awt.Color(255, 255, 255));
        bt51.setForeground(new java.awt.Color(255, 255, 255));
        bt51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt51ActionPerformed(evt);
            }
        });

        bt52.setBackground(new java.awt.Color(0, 0, 0));
        bt52.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt52ActionPerformed(evt);
            }
        });

        bt53.setBackground(new java.awt.Color(255, 255, 255));
        bt53.setForeground(new java.awt.Color(255, 255, 255));
        bt53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt53ActionPerformed(evt);
            }
        });

        bt54.setBackground(new java.awt.Color(0, 0, 0));
        bt54.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt54ActionPerformed(evt);
            }
        });

        bt55.setBackground(new java.awt.Color(255, 255, 255));
        bt55.setForeground(new java.awt.Color(255, 255, 255));
        bt55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt55ActionPerformed(evt);
            }
        });

        bt66.setBackground(new java.awt.Color(255, 255, 255));
        bt66.setForeground(new java.awt.Color(255, 255, 255));
        bt66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt66ActionPerformed(evt);
            }
        });

        bt05.setBackground(new java.awt.Color(0, 0, 0));
        bt05.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt05ActionPerformed(evt);
            }
        });

        bt67.setBackground(new java.awt.Color(0, 0, 0));
        bt67.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt67ActionPerformed(evt);
            }
        });

        bt06.setBackground(new java.awt.Color(255, 255, 255));
        bt06.setForeground(new java.awt.Color(255, 255, 255));
        bt06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt06ActionPerformed(evt);
            }
        });

        bt60.setBackground(new java.awt.Color(255, 255, 255));
        bt60.setForeground(new java.awt.Color(255, 255, 255));
        bt60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt60ActionPerformed(evt);
            }
        });

        bt07.setBackground(new java.awt.Color(0, 0, 0));
        bt07.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt07ActionPerformed(evt);
            }
        });

        bt61.setBackground(new java.awt.Color(0, 0, 0));
        bt61.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt61ActionPerformed(evt);
            }
        });

        bt16.setBackground(new java.awt.Color(0, 0, 0));
        bt16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt16ActionPerformed(evt);
            }
        });

        bt62.setBackground(new java.awt.Color(255, 255, 255));
        bt62.setForeground(new java.awt.Color(255, 255, 255));
        bt62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt62ActionPerformed(evt);
            }
        });

        bt17.setBackground(new java.awt.Color(255, 255, 255));
        bt17.setForeground(new java.awt.Color(255, 255, 255));
        bt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt17ActionPerformed(evt);
            }
        });

        bt63.setBackground(new java.awt.Color(0, 0, 0));
        bt63.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt63ActionPerformed(evt);
            }
        });

        bt10.setBackground(new java.awt.Color(0, 0, 0));
        bt10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        bt64.setBackground(new java.awt.Color(255, 255, 255));
        bt64.setForeground(new java.awt.Color(255, 255, 255));
        bt64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt64ActionPerformed(evt);
            }
        });

        bt11.setBackground(new java.awt.Color(255, 255, 255));
        bt11.setForeground(new java.awt.Color(255, 255, 255));
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });

        bt12.setBackground(new java.awt.Color(0, 0, 0));
        bt12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });

        bt13.setBackground(new java.awt.Color(255, 255, 255));
        bt13.setForeground(new java.awt.Color(255, 255, 255));
        bt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt13ActionPerformed(evt);
            }
        });

        bt14.setBackground(new java.awt.Color(0, 0, 0));
        bt14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt14ActionPerformed(evt);
            }
        });

        bt00.setBackground(new java.awt.Color(255, 255, 255));
        bt00.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt00.setForeground(new java.awt.Color(255, 255, 255));
        bt00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt00ActionPerformed(evt);
            }
        });

        bt01.setBackground(new java.awt.Color(0, 0, 0));
        bt01.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt01ActionPerformed(evt);
            }
        });

        bt02.setBackground(new java.awt.Color(255, 255, 255));
        bt02.setForeground(new java.awt.Color(255, 255, 255));
        bt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt02ActionPerformed(evt);
            }
        });

        bt03.setBackground(new java.awt.Color(0, 0, 0));
        bt03.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt03ActionPerformed(evt);
            }
        });

        bt04.setBackground(new java.awt.Color(255, 255, 255));
        bt04.setForeground(new java.awt.Color(255, 255, 255));
        bt04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt04ActionPerformed(evt);
            }
        });

        bt65.setBackground(new java.awt.Color(0, 0, 0));
        bt65.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt65ActionPerformed(evt);
            }
        });

        bt76.setBackground(new java.awt.Color(0, 0, 0));
        bt76.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt76ActionPerformed(evt);
            }
        });

        bt77.setBackground(new java.awt.Color(255, 255, 255));
        bt77.setForeground(new java.awt.Color(255, 255, 255));
        bt77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt77ActionPerformed(evt);
            }
        });

        bt70.setBackground(new java.awt.Color(0, 0, 0));
        bt70.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt70ActionPerformed(evt);
            }
        });

        bt15.setBackground(new java.awt.Color(255, 255, 255));
        bt15.setForeground(new java.awt.Color(255, 255, 255));
        bt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt15ActionPerformed(evt);
            }
        });

        bt71.setBackground(new java.awt.Color(255, 255, 255));
        bt71.setForeground(new java.awt.Color(255, 255, 255));
        bt71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt71ActionPerformed(evt);
            }
        });

        bt26.setBackground(new java.awt.Color(255, 255, 255));
        bt26.setForeground(new java.awt.Color(255, 255, 255));
        bt26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt26ActionPerformed(evt);
            }
        });

        bt72.setBackground(new java.awt.Color(0, 0, 0));
        bt72.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt72ActionPerformed(evt);
            }
        });

        bt27.setBackground(new java.awt.Color(0, 0, 0));
        bt27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt27ActionPerformed(evt);
            }
        });

        bt73.setBackground(new java.awt.Color(255, 255, 255));
        bt73.setForeground(new java.awt.Color(255, 255, 255));
        bt73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt73ActionPerformed(evt);
            }
        });

        bt20.setBackground(new java.awt.Color(255, 255, 255));
        bt20.setForeground(new java.awt.Color(255, 255, 255));
        bt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt20ActionPerformed(evt);
            }
        });

        bt74.setBackground(new java.awt.Color(0, 0, 0));
        bt74.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt74ActionPerformed(evt);
            }
        });

        bt21.setBackground(new java.awt.Color(0, 0, 0));
        bt21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt21ActionPerformed(evt);
            }
        });

        bt75.setBackground(new java.awt.Color(255, 255, 255));
        bt75.setForeground(new java.awt.Color(255, 255, 255));
        bt75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt75ActionPerformed(evt);
            }
        });

        bt22.setBackground(new java.awt.Color(255, 255, 255));
        bt22.setForeground(new java.awt.Color(255, 255, 255));
        bt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt22ActionPerformed(evt);
            }
        });

        bt23.setBackground(new java.awt.Color(0, 0, 0));
        bt23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt23ActionPerformed(evt);
            }
        });

        bt24.setBackground(new java.awt.Color(255, 255, 255));
        bt24.setForeground(new java.awt.Color(255, 255, 255));
        bt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt24ActionPerformed(evt);
            }
        });

        bt25.setBackground(new java.awt.Color(0, 0, 0));
        bt25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt25ActionPerformed(evt);
            }
        });

        bt36.setBackground(new java.awt.Color(0, 0, 0));
        bt36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt36ActionPerformed(evt);
            }
        });

        bt37.setBackground(new java.awt.Color(255, 255, 255));
        bt37.setForeground(new java.awt.Color(255, 255, 255));
        bt37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt37ActionPerformed(evt);
            }
        });

        bt30.setBackground(new java.awt.Color(0, 0, 0));
        bt30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt30ActionPerformed(evt);
            }
        });

        bt31.setBackground(new java.awt.Color(255, 255, 255));
        bt31.setForeground(new java.awt.Color(255, 255, 255));
        bt31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt31ActionPerformed(evt);
            }
        });

        bt32.setBackground(new java.awt.Color(0, 0, 0));
        bt32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt32ActionPerformed(evt);
            }
        });

        bt33.setBackground(new java.awt.Color(255, 255, 255));
        bt33.setForeground(new java.awt.Color(255, 255, 255));
        bt33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt33ActionPerformed(evt);
            }
        });

        bt34.setBackground(new java.awt.Color(0, 0, 0));
        bt34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt34ActionPerformed(evt);
            }
        });

        bt35.setBackground(new java.awt.Color(255, 255, 255));
        bt35.setForeground(new java.awt.Color(255, 255, 255));
        bt35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt35ActionPerformed(evt);
            }
        });

        bt46.setBackground(new java.awt.Color(255, 255, 255));
        bt46.setForeground(new java.awt.Color(255, 255, 255));
        bt46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt46ActionPerformed(evt);
            }
        });

        bt47.setBackground(new java.awt.Color(0, 0, 0));
        bt47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt47ActionPerformed(evt);
            }
        });

        bt40.setBackground(new java.awt.Color(255, 255, 255));
        bt40.setForeground(new java.awt.Color(255, 255, 255));
        bt40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt40ActionPerformed(evt);
            }
        });

        bt41.setBackground(new java.awt.Color(0, 0, 0));
        bt41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt41ActionPerformed(evt);
            }
        });

        bt42.setBackground(new java.awt.Color(255, 255, 255));
        bt42.setForeground(new java.awt.Color(255, 255, 255));
        bt42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt42ActionPerformed(evt);
            }
        });

        bt43.setBackground(new java.awt.Color(0, 0, 0));
        bt43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt43ActionPerformed(evt);
            }
        });

        bt44.setBackground(new java.awt.Color(255, 255, 255));
        bt44.setForeground(new java.awt.Color(255, 255, 255));
        bt44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt44ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt67))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt70)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt73)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt74)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt00, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt04)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt05)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt06)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt07))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt17)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt00, bt01, bt02, bt03, bt04, bt05, bt06, bt07, bt10, bt11, bt12, bt13, bt14, bt15, bt16, bt17, bt20, bt21, bt22, bt23, bt24, bt25, bt26, bt27, bt30, bt31, bt32, bt33, bt34, bt35, bt36, bt37, bt40, bt41, bt42, bt43, bt44, bt45, bt46, bt47, bt50, bt51, bt52, bt53, bt54, bt55, bt56, bt57, bt60, bt61, bt62, bt63, bt64, bt65, bt66, bt67, bt70, bt71, bt72, bt73, bt74, bt75, bt76, bt77});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt00, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt01)
                    .addComponent(bt02)
                    .addComponent(bt03)
                    .addComponent(bt04)
                    .addComponent(bt05)
                    .addComponent(bt06)
                    .addComponent(bt07))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt10)
                    .addComponent(bt11)
                    .addComponent(bt12)
                    .addComponent(bt13)
                    .addComponent(bt14)
                    .addComponent(bt15)
                    .addComponent(bt16)
                    .addComponent(bt17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt20)
                    .addComponent(bt21)
                    .addComponent(bt22)
                    .addComponent(bt23)
                    .addComponent(bt24)
                    .addComponent(bt25)
                    .addComponent(bt26)
                    .addComponent(bt27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt30)
                    .addComponent(bt31)
                    .addComponent(bt32)
                    .addComponent(bt33)
                    .addComponent(bt34)
                    .addComponent(bt35)
                    .addComponent(bt36)
                    .addComponent(bt37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt40)
                    .addComponent(bt41)
                    .addComponent(bt42)
                    .addComponent(bt43)
                    .addComponent(bt44)
                    .addComponent(bt45)
                    .addComponent(bt46)
                    .addComponent(bt47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt50)
                    .addComponent(bt51)
                    .addComponent(bt52)
                    .addComponent(bt53)
                    .addComponent(bt54)
                    .addComponent(bt55)
                    .addComponent(bt56)
                    .addComponent(bt57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt60)
                    .addComponent(bt61)
                    .addComponent(bt62)
                    .addComponent(bt63)
                    .addComponent(bt64)
                    .addComponent(bt65)
                    .addComponent(bt66)
                    .addComponent(bt67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt70)
                    .addComponent(bt71)
                    .addComponent(bt72)
                    .addComponent(bt73)
                    .addComponent(bt74)
                    .addComponent(bt75)
                    .addComponent(bt76)
                    .addComponent(bt77))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt00, bt01, bt02, bt03, bt04, bt05, bt06, bt07, bt10, bt11, bt12, bt13, bt14, bt15, bt16, bt17, bt20, bt21, bt22, bt23, bt24, bt25, bt26, bt27, bt30, bt31, bt32, bt33, bt34, bt35, bt36, bt37, bt40, bt41, bt42, bt43, bt44, bt45, bt46, bt47, bt50, bt51, bt52, bt53, bt54, bt55, bt56, bt57, bt60, bt61, bt62, bt63, bt64, bt65, bt66, bt67, bt70, bt71, bt72, bt73, bt74, bt75, bt76, bt77});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Jogo da Dama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 15))); // NOI18N

        jLabel2.setText("Jogador 01 Pedra Vermelha: ");

        jLabel3.setText("Jogador 02 Pedra Amarela: ");

        NumeroDeVitoriasDoJogador01.setText("Numero de Vitórias: 0");

        NumeroDeVitóriasDoJogaador02.setText("Numero de Vitórias: 0");

        NumeroDeEmpates.setText("Numero de empates: 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(NumeroDeEmpates)
                            .addComponent(NumeroDeVitoriasDoJogador01))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(NumeroDeVitóriasDoJogaador02))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(NumeroDeVitoriasDoJogador01)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroDeVitóriasDoJogaador02)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroDeEmpates)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle do Jogo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 15))); // NOI18N

        btNovoJogo.setText("Novo Jogo");

        btSobreJogo.setText("Sobre o Jogo");

        btSairJogo.setText("Sair do jogo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSobreJogo)
                    .addComponent(btSairJogo))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btNovoJogo, btSairJogo, btSobreJogo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btSobreJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSairJogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btNovoJogo, btSairJogo, btSobreJogo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1002, 645));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt40ActionPerformed

    private void bt46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt46ActionPerformed

    private void bt30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt30ActionPerformed

    private void bt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt20ActionPerformed

    private void bt70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt70ActionPerformed

    private void bt01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt01ActionPerformed
       // pedrasJogador1(); //teste aqui chama o metodo quando clico em uma casa depois de execultado
        /* 
        //criar a pedra do jogo quando eu clico depois de executado
       if (jogador1Ativo == true) {
            if (bt00.getText().equals("")) {
                bt00.setText("O");
               
                bt00.setForeground(Color.red);//aqui muda a cor da fonte
                jogadorAtivo();           
            } 
        } else{
            if (bt00.getText().equals("")) {
                bt00.setText("X");
                jogadorAtivo();           
            } 
        }*/
    }//GEN-LAST:event_bt01ActionPerformed

    private void bt00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt00ActionPerformed
      
       
        
    }//GEN-LAST:event_bt00ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt60ActionPerformed

    private void bt50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt50ActionPerformed

    private void bt02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt02ActionPerformed

    private void bt03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt03ActionPerformed
        // pedrasJogador1(); //teste aqui chama o metodo quando clico em uma casa depois de execultado
        /* 
        //criar a pedra do jogo quando eu clico depois de executado
       if (jogador1Ativo == true) {
            if (bt00.getText().equals("")) {
                bt00.setText("O");
               
                bt00.setForeground(Color.red);//aqui muda a cor da fonte
                jogadorAtivo();           
            } 
        } else{
            if (bt00.getText().equals("")) {
                bt00.setText("X");
                jogadorAtivo();           
            } 
        }*/
    }//GEN-LAST:event_bt03ActionPerformed

    private void bt04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt04ActionPerformed

    private void bt05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt05ActionPerformed
       // pedrasJogador1(); //teste aqui chama o metodo quando clico em uma casa depois de execultado
        /* 
        //criar a pedra do jogo quando eu clico depois de executado
       if (jogador1Ativo == true) {
            if (bt00.getText().equals("")) {
                bt00.setText("O");
               
                bt00.setForeground(Color.red);//aqui muda a cor da fonte
                jogadorAtivo();           
            } 
        } else{
            if (bt00.getText().equals("")) {
                bt00.setText("X");
                jogadorAtivo();           
            } 
        }*/
    }//GEN-LAST:event_bt05ActionPerformed

    private void bt06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt06ActionPerformed

    private void bt07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt07ActionPerformed
       // pedrasJogador1(); //teste aqui chama o metodo quando clico em uma casa depois de execultado
        /* 
        //criar a pedra do jogo quando eu clico depois de executado
       if (jogador1Ativo == true) {
            if (bt00.getText().equals("")) {
                bt00.setText("O");
               
                bt00.setForeground(Color.red);//aqui muda a cor da fonte
                jogadorAtivo();           
            } 
        } else{
            if (bt00.getText().equals("")) {
                bt00.setText("X");
                jogadorAtivo();           
            } 
        }*/
    }//GEN-LAST:event_bt07ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt13ActionPerformed

    private void bt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt14ActionPerformed

    private void bt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt15ActionPerformed

    private void bt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt16ActionPerformed

    private void bt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt17ActionPerformed

    private void bt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt21ActionPerformed

    private void bt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt22ActionPerformed

    private void bt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt23ActionPerformed

    private void bt24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt24ActionPerformed

    private void bt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt25ActionPerformed

    private void bt26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt26ActionPerformed

    private void bt27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt27ActionPerformed

    private void bt31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt31ActionPerformed

    private void bt32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt32ActionPerformed

    private void bt33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt33ActionPerformed

    private void bt34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt34ActionPerformed

    private void bt35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt35ActionPerformed

    private void bt36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt36ActionPerformed

    private void bt37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt37ActionPerformed

    private void bt41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt41ActionPerformed

    private void bt42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt42ActionPerformed

    private void bt43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt43ActionPerformed

    private void bt44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt44ActionPerformed

    private void bt45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt45ActionPerformed

    private void bt47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt47ActionPerformed

    private void bt51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt51ActionPerformed

    private void bt52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt52ActionPerformed

    private void bt53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt53ActionPerformed

    private void bt54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt54ActionPerformed

    private void bt55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt55ActionPerformed

    private void bt56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt56ActionPerformed

    private void bt57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt57ActionPerformed

    private void bt61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt61ActionPerformed

    private void bt62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt62ActionPerformed

    private void bt64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt64ActionPerformed

    private void bt65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt65ActionPerformed

    private void bt66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt66ActionPerformed

    private void bt67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt67ActionPerformed

    private void bt71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt71ActionPerformed

    private void bt72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt72ActionPerformed

    private void bt73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt73ActionPerformed

    private void bt74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt74ActionPerformed

    private void bt75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt75ActionPerformed

    private void bt76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt76ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_bt76ActionPerformed

    private void bt77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt77ActionPerformed

    private void bt63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt63ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabuleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumeroDeEmpates;
    private javax.swing.JLabel NumeroDeVitoriasDoJogador01;
    private javax.swing.JLabel NumeroDeVitóriasDoJogaador02;
    private javax.swing.JButton bt00;
    private javax.swing.JButton bt01;
    private javax.swing.JButton bt02;
    private javax.swing.JButton bt03;
    private javax.swing.JButton bt04;
    private javax.swing.JButton bt05;
    private javax.swing.JButton bt06;
    private javax.swing.JButton bt07;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt17;
    private javax.swing.JButton bt20;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.JButton bt23;
    private javax.swing.JButton bt24;
    private javax.swing.JButton bt25;
    private javax.swing.JButton bt26;
    private javax.swing.JButton bt27;
    private javax.swing.JButton bt30;
    private javax.swing.JButton bt31;
    private javax.swing.JButton bt32;
    private javax.swing.JButton bt33;
    private javax.swing.JButton bt34;
    private javax.swing.JButton bt35;
    private javax.swing.JButton bt36;
    private javax.swing.JButton bt37;
    private javax.swing.JButton bt40;
    private javax.swing.JButton bt41;
    private javax.swing.JButton bt42;
    private javax.swing.JButton bt43;
    private javax.swing.JButton bt44;
    private javax.swing.JButton bt45;
    private javax.swing.JButton bt46;
    private javax.swing.JButton bt47;
    private javax.swing.JButton bt50;
    private javax.swing.JButton bt51;
    private javax.swing.JButton bt52;
    private javax.swing.JButton bt53;
    private javax.swing.JButton bt54;
    private javax.swing.JButton bt55;
    private javax.swing.JButton bt56;
    private javax.swing.JButton bt57;
    private javax.swing.JButton bt60;
    private javax.swing.JButton bt61;
    private javax.swing.JButton bt62;
    private javax.swing.JButton bt63;
    private javax.swing.JButton bt64;
    private javax.swing.JButton bt65;
    private javax.swing.JButton bt66;
    private javax.swing.JButton bt67;
    private javax.swing.JButton bt70;
    private javax.swing.JButton bt71;
    private javax.swing.JButton bt72;
    private javax.swing.JButton bt73;
    private javax.swing.JButton bt74;
    private javax.swing.JButton bt75;
    private javax.swing.JButton bt76;
    private javax.swing.JButton bt77;
    private javax.swing.JButton btNovoJogo;
    private javax.swing.JButton btSairJogo;
    private javax.swing.JButton btSobreJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void jogadorAtivo() {
        
        //to do: Criar a logica do jogo aqui
    }
    private void pedrasJogador1(){
    
            if ((bt01.getText().equals("")) && (bt03.getText().equals("")) && (bt05.getText().equals("")) && (bt07.getText().equals("")) 
                    && (bt10.getText().equals("")) && (bt12.getText().equals("")) && (bt14.getText().equals(""))&& (bt16.getText().equals("")) 
                    && (bt21.getText().equals("")) && (bt23.getText().equals("")) && (bt25.getText().equals("")) && (bt27.getText().equals("")))
            {
                //-----linha 01--------------------------------------------
                bt01.setText("O"); //aqui grava "O" nas casas              
                bt01.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt03.setText("O"); //aqui grava "O" nas casas              
                bt03.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt05.setText("O"); //aqui grava "O" nas casas              
                bt05.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt07.setText("O"); //aqui grava "O" nas casas              
                bt07.setForeground(Color.red);//aqui muda a cor da fonte
                
                //-----linha 02--------------------------------------------
                //=================
                bt10.setText("O"); //aqui grava "O" nas casas              
                bt10.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt12.setText("O"); //aqui grava "O" nas casas              
                bt12.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt14.setText("O"); //aqui grava "O" nas casas              
                bt14.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt16.setText("O"); //aqui grava "O" nas casas              
                bt16.setForeground(Color.red);//aqui muda a cor da fonte
                
                 //-----linha 03--------------------------------------------
                //=================
                bt21.setText("O"); //aqui grava "O" nas casas              
                bt21.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt23.setText("O"); //aqui grava "O" nas casas              
                bt23.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt25.setText("O"); //aqui grava "O" nas casas               
                bt25.setForeground(Color.red);//aqui muda a cor da fonte
                
                //=================
                bt27.setText("O"); //aqui grava "O" nas casas              
                bt27.setForeground(Color.red);//aqui muda a cor da fonte
            }          
    }
    private void pedrasJogador2(){
    
        if ((bt70.getText().equals("")) && (bt72.getText().equals("")) && (bt74.getText().equals("")) && (bt76.getText().equals(""))
               && (bt61.getText().equals("")) && (bt63.getText().equals("")) && (bt65.getText().equals("")) && (bt67.getText().equals(""))
                && (bt50.getText().equals("")) && (bt52.getText().equals("")) && (bt54.getText().equals("")) && (bt56.getText().equals("")))
        {// se a casa estiver vazia preencre com "O"
            
            //-----linha 08--------------------------------------------
                bt70.setText("O"); //aqui grava "O" nas casas              
                bt70.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=================
                bt72.setText("O"); //aqui grava "O" nas casas              
                bt72.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=============
                bt74.setText("O"); //aqui grava "O" nas casas              
                bt74.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=============
                bt76.setText("O"); //aqui grava "O" nas casas              
                bt76.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                 //-----linha 07--------------------------------------------
                bt61.setText("O"); //aqui grava "O" nas casas              
                bt61.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=================
                bt63.setText("O"); //aqui grava "O" nas casas              
                bt63.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=============
                bt65.setText("O"); //aqui grava "O" nas casas              
                bt65.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=============
                bt67.setText("O"); //aqui grava "O" nas casas              
                bt67.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                 //-----linha 06--------------------------------------------
                bt50.setText("O"); //aqui grava "O" nas casas              
                bt50.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=================
                bt52.setText("O"); //aqui grava "O" nas casas              
                bt52.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=============
                bt54.setText("O"); //aqui grava "O" nas casas              
                bt54.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
                //=============
                bt56.setText("O"); //aqui grava "O" nas casas              
                bt56.setForeground(Color.YELLOW);//aqui muda a cor da fonte
                
            }     
    }
//metodo para decidir qual jogador foi o vencedor
    private void jogadorVencedor(String jogador) {
        
        if (rootPaneCheckingEnabled) {
            
        }
    }
    
    //refazer isso aqui
    private void moverPecas(){
        
        if ((bt21.getText().equals("O")))  {
            bt21.setText("");
            
        } 
    }
}
